[package]
name = "bevy-discord-presence"
description = "Discord presence plugin for the Bevy game engine"
license = "MIT"
authors = ["Juliette Cordor"]
keywords = ["discord", "rpc", "ipc"]
version = "0.4.3"
repository  = "https://github.com/jewlexx/discord-presence.git"
edition = "2021"

[dependencies]
discord-presence = { version = "0.6.0", git = "https://github.com/jewlexx/discord-presence", branch= "v0.6" }
bevy = { version = ">=0.9", default-features = false }
parking_lot = "0.12"
quork = { version = "0.4.0", default-features = false, features = ["traits"] }
derive_more = "0.99.17"

[dev-dependencies]
version-sync = "0.9"
